name: Update Dune Data

on:
  schedule:
    - cron: '0 */8 * * *'
  push:
    branches:
      - main

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dune-client

    - name: Create empty badge_data.json
      run: echo '{}' > badge_data.json

    - name: Fetch data from Dune
      env:
        DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
      run: |
        python fetch_badges.py
      working-directory: ./ 

    - name: Commit and push changes
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add badge_data.json
        git commit -m 'Update badge data' || echo "Nothing to commit"
        git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/mimika-code/Canvas.git || echo "Push failed"
